# Generated by Django 4.2.9 on 2024-08-20 11:31

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MidasConfigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_run', models.IntegerField(default=4)),
                ('gen_path', models.CharField(blank=True, default='Input path', max_length=512)),
                ('civil_path', models.CharField(blank=True, default='Input path', max_length=512)),
                ('gts_path', models.CharField(blank=True, default='Input path', max_length=512)),
                ('fea_path', models.CharField(blank=True, default='Input path', max_length=512)),
                ('nfx_path', models.CharField(blank=True, default='Input path', max_length=512)),
                ('mec_path', models.CharField(blank=True, default='Input path', max_length=512)),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='MidasModelFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=home.models.directory_path)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='NONE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Model File',
                'verbose_name_plural': 'Model Files',
                'ordering': ['created_at'],
            },
        ),
    ]
