# Generated by Django 4.2.9 on 2024-08-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midasconfigure',
            name='mec_path',
        ),
    ]
