# Generated by Django 4.2.9 on 2024-08-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_midasconfigure_mec_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='midasmodelfile',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='midasmodelfile',
            name='stdout',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='midasmodelfile',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
