# Generated by Django 4.2.9 on 2024-08-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_midasmodelfile_executed_at_midasmodelfile_stdout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midasmodelfile',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
